baseurl = "https://www.prakhrr.github.io/"
title = "Prakhar"
canonifyurls = true
languagecode = "en-us"
theme = "black-and-light"
publishDir = "https://www.prakhrr.github.io/"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Prakhar"
  disableWebFonts = false

[[menu.main]]
    name = "About"
    url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"
[[menu.main]]
    name = "Projects"
    url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"
[[menu.main]]
    name = "Resume"
    url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"
